apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perfseer-v3-a10-nonvision-labels
  namespace: REPLACE_NAMESPACE
  labels:
    app.kubernetes.io/name: perfseer-v3-a10-nonvision-labeler
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Gi
  storageClassName: rook-cephfs
