apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perfseer-v3-v100-labels
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Gi
  storageClassName: rook-cephfs
