"""PerfSeer v3 graph capture, feature, model, and deployment package."""

from .version import (
    FEATURE_SCHEMA_VERSION,
    GRAPH_IR_VERSION,
    HARDWARE_NORMALIZATION_VERSION,
    HARDWARE_PROFILE_VERSION,
    LABEL_SCHEMA_VERSION,
    OP_REGISTRY_VERSION,
    OUTPUT_CONTRACT_VERSION,
    STUDENT_MODEL_RELEASE,
    TEACHER_MODEL_RELEASE,
    TRANSFER_ARTIFACT_VERSION,
    TRANSFER_MANIFEST_VERSION,
    WORKLOAD_NORMALIZATION_VERSION,
)

__all__ = [
    "FEATURE_SCHEMA_VERSION",
    "GRAPH_IR_VERSION",
    "HARDWARE_NORMALIZATION_VERSION",
    "HARDWARE_PROFILE_VERSION",
    "LABEL_SCHEMA_VERSION",
    "OP_REGISTRY_VERSION",
    "OUTPUT_CONTRACT_VERSION",
    "STUDENT_MODEL_RELEASE",
    "TEACHER_MODEL_RELEASE",
    "TRANSFER_ARTIFACT_VERSION",
    "TRANSFER_MANIFEST_VERSION",
    "WORKLOAD_NORMALIZATION_VERSION",
]
