"""Independent version namespaces used by PerfSeer v3 artifacts."""

GRAPH_IR_VERSION = "perfseer_ir_v3"
FEATURE_SCHEMA_VERSION = "perfseer_graph_v3_transfer_v1"
LABEL_SCHEMA_VERSION = "scheduler_resource_label_v3"
OP_REGISTRY_VERSION = "perfseer_aten_ops_v3"
TEACHER_MODEL_RELEASE = "perfseer_v3_teacher"
STUDENT_MODEL_RELEASE = "perfseer_v3_student"
WORKLOAD_NORMALIZATION_VERSION = "perfseer_v3_workload_normalization_v2"
HARDWARE_PROFILE_VERSION = "perfseer_v3_hardware_profile_v1"
HARDWARE_NORMALIZATION_VERSION = "perfseer_v3_hardware_normalization_v1"
TRANSFER_MANIFEST_VERSION = "perfseer_v3_transfer_manifest_v1"
TRANSFER_ARTIFACT_VERSION = "perfseer_v3_transfer_artifact_v1"
OUTPUT_CONTRACT_VERSION = "perfseer_v3_outputs_v3_transfer"
